version: '3.8'

services:
  # sync-web:
  #   build: .
  #   ports:
  #     - "8181:8181"
  #   environment:
  #     DATABASE_URL: postgres://postgres:password@db/development
  db:
    image: redis:7.2.4-alpine3.19
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: development
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
